services:
  # 1. The Queue (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # The port for code to talk to
      - "15672:15672" # GUI dashboard
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # 2. Object Storage (MinIO)
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Web UI port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

  # 3. The Database (PostgreSQL) 
  # For keeping track of "Job Status" (Pending, Failed, Success)
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobs_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d jobs_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

# ... existing services (db, rabbitmq, minio) ...

  # Get metrics
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: rce-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:Z
    ports:
      - "9090:9090"
    # For Linux Podman/Docker to see the host
    extra_hosts:
      - "host.containers.internal:host-gateway" 

  # Visualize
  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: rce-grafana
    user: "0"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
          - ./grafana_config:/etc/grafana/provisioning/datasources:Z
  
    # Worker
  worker:
      build: 
        context: .
        dockerfile: Dockerfile
      container_name: rce-worker
      restart: on-failure:5
      env_file:
        - .env
      environment:
        RABBITMQ_HOST: rabbitmq
        POSTGRES_HOST: db
        MINIO_ENDPOINT: minio:9000
      depends_on:
        rabbitmq:
          condition: service_healthy
        db:
          condition: service_healthy
      volumes:
        - .:/app:Z 
        - /run/user/1000/podman/podman.sock:/run/podman/podman.sock:z
      security_opt:
        - label=disable
      command: uv run worker/main.py
volumes:
  rabbitmq_data:
  minio_data:
  postgres_data: